<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $locations = [
            ["name" => "Laoag City, Ilocos Norte", "rdo_id" => 1],
            ["name" => "Vigan, Ilocos Sur", "rdo_id" => 2],
            ["name" => "San Fernando, La Union", "rdo_id" => 3],
            ["name" => "Calasiao, West Pangasinan", "rdo_id" => 4],
            ["name" => "Alaminos, Pangasinan", "rdo_id" => 5],
            ["name" => "Urdaneta, Pangasinan", "rdo_id" => 6],
            ["name" => "Bangued, Abra", "rdo_id" => 7],
            ["name" => "Baguio City", "rdo_id" => 8],
            ["name" => "La Trinidad, Benguet", "rdo_id" => 9],
            ["name" => "Bontoc, Mt. Province", "rdo_id" => 10],
            ["name" => "Tabuk City, Kalinga", "rdo_id" => 11],
            ["name" => "Lagawe, Ifugao", "rdo_id" => 12],
            ["name" => "Tuguegarao, Cagayan", "rdo_id" => 13],
            ["name" => "Bayombong, Nueva Vizcaya", "rdo_id" => 14],
            ["name" => "Naguilian, Isabela", "rdo_id" => 15],
            ["name" => "Cabarroguis, Quirino", "rdo_id" => 16],
            ["name" => "Tarlac City, Tarlac", "rdo_id" => 17],
            ["name" => "Paniqui, Tarlac", "rdo_id" => 18],
            ["name" => "Olongapo City", "rdo_id" => 19],
            ["name" => "Subic Bay Freeport Zone", "rdo_id" => 20],
            ["name" => "Balanga, Bataan", "rdo_id" => 21],
            ["name" => "North Pampanga", "rdo_id" => 22],
            ["name" => "South Pampanga", "rdo_id" => 23],
            ["name" => "Clark Freeport Zone", "rdo_id" => 24],
            ["name" => "Baler, Aurora", "rdo_id" => 25],
            ["name" => "North Nueva Ecija", "rdo_id" => 26],
            ["name" => "South Nueva Ecija", "rdo_id" => 27],
            ["name" => "Valenzuela City", "rdo_id" => 28],
            ["name" => "Plaridel, Bulacan", "rdo_id" => 29],
            ["name" => "Sta. Maria, Bulacan", "rdo_id" => 30],
            ["name" => "Malabon-Navotas", "rdo_id" => 31],
            ["name" => "Caloocan City", "rdo_id" => 32],
            ["name" => "Novaliches", "rdo_id" => 33],
            ["name" => "Tondo - San Nicolas", "rdo_id" => 34],
            ["name" => "Binondo", "rdo_id" => 35],
            ["name" => "Sta. Cruz", "rdo_id" => 36],
            ["name" => "Quiapo-Sampaloc-San Miguel-Sta. Mesa", "rdo_id" => 37],
            ["name" => "Intramuros-Ermita-Malate", "rdo_id" => 38],
            ["name" => "Paco-Pandacan-Sta. Ana-San Andres", "rdo_id" => 39],
            ["name" => "Romblon", "rdo_id" => 40],
            ["name" => "Puerto Princesa", "rdo_id" => 41],
            ["name" => "San Jose, Occidental Mindoro", "rdo_id" => 42],
            ["name" => "North Quezon City", "rdo_id" => 43],
            ["name" => "South Quezon City", "rdo_id" => 44],
            ["name" => "Cubao", "rdo_id" => 45],
            ["name" => "Mandaluyong City", "rdo_id" => 46],
            ["name" => "San Juan", "rdo_id" => 47],
            ["name" => "Pasig", "rdo_id" => 48],
            ["name" => "Taguig-Pateros", "rdo_id" => 49],
            ["name" => "Marikina", "rdo_id" => 50],
            ["name" => "Cainta-Taytay", "rdo_id" => 51],
            ["name" => "East Makati", "rdo_id" => 52],
            ["name" => "West Makati", "rdo_id" => 53],
            ["name" => "North Makati", "rdo_id" => 54],
            ["name" => "South Makati", "rdo_id" => 55],
            ["name" => "Pasay City", "rdo_id" => 56],
            ["name" => "Parañaque", "rdo_id" => 57],
            ["name" => "Las Piñas City", "rdo_id" => 58],
            ["name" => "Muntinlupa City", "rdo_id" => 59],
            ["name" => "Trece Martirez City, East Cavite", "rdo_id" => 60],
            ["name" => "Kawit, West Cavite", "rdo_id" => 61],
            ["name" => "San Pablo City", "rdo_id" => 62],
            ["name" => "Calamba, Laguna", "rdo_id" => 63],
            ["name" => "Biñan, Laguna", "rdo_id" => 64],
            ["name" => "Batangas City", "rdo_id" => 65],
            ["name" => "Lipa City", "rdo_id" => 66],
            ["name" => "Lucena City", "rdo_id" => 67],
            ["name" => "Gumaca, Quezon", "rdo_id" => 68],
            ["name" => "Boac, Marinduque", "rdo_id" => 69],
            ["name" => "Calapan, Oriental Mindoro", "rdo_id" => 70],
            ["name" => "Talisay, Camarines Norte", "rdo_id" => 71],
            ["name" => "Naga City", "rdo_id" => 72],
            ["name" => "Iriga City", "rdo_id" => 73],
            ["name" => "Legazpi City, Albay", "rdo_id" => 74],
            ["name" => "Sorsogon, Sorsogon", "rdo_id" => 75],
            ["name" => "Virac, Catanduanes", "rdo_id" => 76],
            ["name" => "Masbate, Masbate", "rdo_id" => 77],
            ["name" => "Kalibo, Aklan", "rdo_id" => 78],
            ["name" => "Roxas City", "rdo_id" => 79],
            ["name" => "San Jose, Antique", "rdo_id" => 80],
            ["name" => "Iloilo City", "rdo_id" => 81],
            ["name" => "Zarraga, Iloilo City", "rdo_id" => 82],
            ["name" => "Victorias City, Negros Occidental", "rdo_id" => 83],
            ["name" => "Bacolod City", "rdo_id" => 84],
            ["name" => "Binalbagan, Negros Occidental", "rdo_id" => 85],
            ["name" => "Dumaguete City", "rdo_id" => 86],
            ["name" => "Mandaue City", "rdo_id" => 87],
            ["name" => "Cebu City North", "rdo_id" => 88],
            ["name" => "Cebu City South", "rdo_id" => 89],
            ["name" => "Talisay City, Cebu", "rdo_id" => 90],
            ["name" => "Tagbilaran City", "rdo_id" => 91],
            ["name" => "Catarman, Northern Samar", "rdo_id" => 92],
            ["name" => "Borongan, Eastern Samar", "rdo_id" => 93],
            ["name" => "Calbayog City, Samar", "rdo_id" => 94],
            ["name" => "Tacloban City", "rdo_id" => 95],
            ["name" => "Ormoc City", "rdo_id" => 96],
            ["name" => "Maasin, Southern Leyte", "rdo_id" => 97],
            ["name" => "Dipolog City", "rdo_id" => 98],
            ["name" => "Pagadian City, Zamboanga del Sur", "rdo_id" => 99],
            ["name" => "Zamboanga City, Zamboanga del Sur", "rdo_id" => 100],
            ["name" => "Ipil, Zamboanga Sibugay", "rdo_id" => 101],
            ["name" => "Isabela, Basilan", "rdo_id" => 102],
            ["name" => "Jolo, Sulu", "rdo_id" => 103],
            ["name" => "Bongao, Tawi-Tawi", "rdo_id" => 104],
            ["name" => "Gingoog City", "rdo_id" => 105],
            ["name" => "Cagayan de Oro City", "rdo_id" => 106],
            ["name" => "Malaybalay City, Bukidnon", "rdo_id" => 107],
            ["name" => "Ozamis City", "rdo_id" => 108],
            ["name" => "Iligan City", "rdo_id" => 109],
            ["name" => "Marawi City", "rdo_id" => 110],
            ["name" => "Butuan City", "rdo_id" => 111],
            ["name" => "Bayugan City, Agusan del Sur", "rdo_id" => 112],
            ["name" => "Surigao City", "rdo_id" => 113],
            ["name" => "Tandag, Surigao del Sur", "rdo_id" => 114],
            ["name" => "Cotabato City", "rdo_id" => 115],
            ["name" => "Kidapawan, North Cotabato", "rdo_id" => 116],
            ["name" => "Tacurong, Sultan Kudarat", "rdo_id" => 117],
            ["name" => "General Santos City", "rdo_id" => 118],
            ["name" => "Koronadal City, South Cotabato", "rdo_id" => 119],
            ["name" => "Tagum, Davao del Norte", "rdo_id" => 120],
            ["name" => "West Davao City", "rdo_id" => 121],
            ["name" => "East Davao City", "rdo_id" => 122],
            ["name" => "Mati, Davao Oriental", "rdo_id" => 123],
            ["name" => "Digos, Davao del Sur", "rdo_id" => 124],
        ];

        foreach ($locations as $location) {
            Location::create($location);
        }
    }
}
